/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author user
 */
public class PenampilGambarFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarFullScreen
     */
    public PenampilGambarFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gmbr1Btn = new javax.swing.JButton();
        gmbrBtn2 = new javax.swing.JButton();
        gmbrBtn3 = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        gmbr1Btn.setText("Gambar 1");
        gmbr1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmbr1BtnActionPerformed(evt);
            }
        });
        jPanel1.add(gmbr1Btn);

        gmbrBtn2.setText("Gambar 2");
        gmbrBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmbrBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(gmbrBtn2);

        gmbrBtn3.setText("Gambar 3");
        gmbrBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmbrBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(gmbrBtn3);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\evos.jpeg")); // NOI18N
        imagePanel.add(jLabel1, "1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Dokumen\\btr.jpg")); // NOI18N
        imagePanel.add(jLabel2, "2");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Dokumen\\onic.jpeg")); // NOI18N
        imagePanel.add(jLabel3, "3");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gmbr1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmbr1BtnActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) (imagePanel.getLayout());
        c1.show(imagePanel, "1");
    }//GEN-LAST:event_gmbr1BtnActionPerformed

    private void gmbrBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmbrBtn2ActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) (imagePanel.getLayout());
        c1.show(imagePanel, "2");
    }//GEN-LAST:event_gmbrBtn2ActionPerformed

    private void gmbrBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmbrBtn3ActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) (imagePanel.getLayout());
        c1.show(imagePanel, "3");
    }//GEN-LAST:event_gmbrBtn3ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run () {
                
                PenampilGambarButton fullframe = new PenampilGambarButton();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullframe);
                
                fullframe.setVisible(true);
                
            } 
         });
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambarFullScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton gmbr1Btn;
    private javax.swing.JButton gmbrBtn2;
    private javax.swing.JButton gmbrBtn3;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
